### ISSUE TITLE
Context Explorer: Heading Not Showing in 0.7.10 Update Please Fix The Issue :(

### ISSUE THREAD

**Issue by paranjay245** [Make-md/makemd#104]
### The 0.7.10 Latest Update Doesnt Shows Heading -- is it deliberate/Conscious Action if yes then please include it in options to enable/disable for those who wanted to utilise! & it isn't mentioned in updateLog! 
![CleanShot 2023-04-18 at 15 23 16@2x](https://user-images.githubusercontent.com/120307516/232741798-15cb715e-e307-4dc9-a1fe-85fa4abf3ab7.png)
### In Previous Updates it Used To Show In Context Explorer! 
![CleanShot 2023-04-18 at 15 24 11@2x](https://user-images.githubusercontent.com/120307516/232742025-7e2492d2-ea6c-4fa4-804c-aa0494ed47b7.png)

**Comment by jp-cen** [comment]
Will be fixed in next patch!

**Comment by paranjay245** [comment]
ayy thank you soo much
