### ISSUE TITLE
Folder Note view ignoring window width

### ISSUE THREAD

**Issue by Peeeet** [Make-md/makemd#107]
In the folder note view for a folder note, it is not expanding or contracting the note to match the width available when you change the overall Obsidian window size.

**Comment by jp-cen** [comment]
This has been patched in the latest version

**Comment by Peeeet** [comment]
FYI unless I have some setting mixed up somewhere or an errant CSS declaration, this still doesn't seem to be fixed for me in the latest version (0.7.18)
