### ISSUE TITLE
trying to add a property with context of a folder doesn't work

### ISSUE THREAD

**Issue by Peeeet** [Make-md/makemd#111]
When clicking "+ Add Property" in folder note view and trying to set the property's context to a folder (instead of just "File Metadata") the "Save Property" button / link (whatever you want to call it) doesn't respond and no error presents itself in the upper right corner.  The button must be working because if you don't enter a name and click "Save Property" it will tell you that the property needs a name.

The "Cancel" button / link / whatever it's called works properly though.  Also "Save Property" works fine if you choose "File Metadata"

**Comment by jp-cen** [comment]
This has been patched, thanks for reporting this
