### ISSUE TITLE
regression: file tree plugin can'T open on start. Always opens on Spaces tab

### ISSUE THREAD

**Issue by ksdavidc** [Make-md/makemd#127]
As noted in the discord server https://discord.com/channels/799706244264362024/1037512613220843540/1105194105048399905 , it used to be that spaces would always be the startup tab, overriding other plugins that tried to be the startup tab, like file tree plugin. This was fixed in some update, but now it has returned...at least for me...

**Comment by jp-cen** [comment]
Do you have Spaces Compatibility mode is on?

**Comment by jp-cen** [comment]
There is now an option to control this and should be fixed

**Comment by ksdavidc** [comment]
Hi. I am sorry to report this is NOT working for me in my sandbox. I have updated Make 0.7.17, Obsidian 1.3.5, File Tree 2.3.4. on mac  12.6.6

https://github.com/Make-md/makemd/assets/62230004/120cb927-947a-438e-bc6e-4cdeb213f248

**Comment by jp-cen** [comment]
The issue should be fixed in the new patch, let me know if it works with your setup

**Comment by ksdavidc** [comment]
Hip Hip Hooray! Works as advertised. Thank you!!!!!!!
