### ISSUE TITLE
It may lead to the creation of new indexes after restarting Obsidian, every time.

### ISSUE THREAD

**Issue by jkjoker** [Make-md/makemd#14]
It may lead to the creation of new indexes after restarting Obsidian. and create new indexes every time.

This was encountered 7 days ago when it was used. It may have been repaired now.

**Comment by jp-cen** [comment]
The index is dependent on the plugin settings. If the plugin setting was removed during sync/uninstall/corruption then the index is rebuilt. Let me know if you experience this again.
