### ISSUE TITLE
Bug: the 0.7.16 version auto open empty tab

### ISSUE THREAD

**Issue by gy-git** [Make-md/makemd#143]
the 0.7.16 auto open empty tab on startup，and even create three or four empty tabs

**Comment by arBorghi** [comment]
Same issue here. It happens when clicking a pinned tab

**Comment by m-primo** [comment]
I have the same issue, and I was just going to report it too. Happens when only clicking on pinned tabs.

**Comment by jp-cen** [comment]
Patched in new release, thanks for reporting this!
