### ISSUE TITLE
Type : for emoji

### ISSUE THREAD

**Issue by bastienperez** [Make-md/makemd#16]
Hello,

Can we get an option to configure/disable the shortcut `:` for emoji popup?

Thanks

**Comment by jp-cen** [comment]
The setting is not exposed, but it is editable if you go into the data.json file for Make.md settings. Going to reorganize the settings a bit in the next release

**Comment by bastienperez** [comment]
Thanks for the info, I have modified this file and will keep checking for future versions ;).
