### ISSUE TITLE
BUG: can't disable backlinks in inline context

### ISSUE THREAD

**Issue by Morganwan90** [Make-md/makemd#168]
Try to disable inline backlink in setting, but it didn't work.

![截图_20230728232015](https://github.com/Make-md/makemd/assets/61633409/371866a1-42e5-4d16-baa2-4044ca2c6c88)

**Comment by jp-cen** [comment]
Thanks for catching this, this is being patched today

**Comment by jp-cen** [comment]
Fixed in the latest patch
