### ISSUE TITLE
Can't disable 'inline stickers'

### ISSUE THREAD

**Issue by JabaDisa** [Make-md/makemd#173]
Regardless of the state of the 'Inline stickers' toggle under 'Flow Styler' in the settings, if I type ':' into a note, the sticker/emoji popup shows up. I would like another plugin to manage this functionality, but can't seem to turn the makemd one off.
Cheers

**Comment by jp-cen** [comment]
You might need to restart the app after turning it off

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: JabaDisa ***@***.***>
Sent: Friday, August 4, 2023 10:14:39 AM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Can't disable 'inline stickers' (Issue #173)


Regardless of the state of the 'Inline stickers' toggle under 'Flow Styler' in the settings, if I type ':' into a note, the sticker/emoji popup shows up. I would like another plugin to manage this functionality, but can't seem to turn the makemd one off.
Cheers

**Comment by JabaDisa** [comment]
I had tried restarting the app, the suggester still pops up, sorry I forgot to mention it.
Just tried on a new vault as well, to rule out any cross-plugin problems - no luck.
For the time being I've set `"emojiTriggerChar": ""` in `data.json` as a workaround.

**Comment by jp-cen** [comment]
The bug has been patched in the latest version, thanks for reporting!
