### ISSUE TITLE
Context Explorer: backlinks triggered "Probation Period Has Ended"

### ISSUE THREAD

**Issue by swuphoto** [Make-md/makemd#174]
Every time I expand the Backlinks, an error message says "The probation period has ended or active code has expired".

**Comment by jp-cen** [comment]
A quick search shows this has to do with the markmind plug-in.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: swuphoto ***@***.***>
Sent: Sunday, August 6, 2023 11:01:52 AM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Context Explorer: backlinks triggered "Probation Period Has Ended" (Issue #174)


Every time I expand the Backlinks, an error message says "The probation period has ended or active code has expired".
