### ISSUE TITLE
Makemd makes the # symbol for headings disappear

### ISSUE THREAD

**Issue by Liong1976** [Make-md/makemd#18]
First, I would like to thank you for creating this fantastic plugin.

I am concerned that this plugin makes the symbol of # for headers disappear in LP when I put the cursor in the heading.

This is the screenshot when the plugin is disabled.

![image](https://user-images.githubusercontent.com/88898230/208212222-e82435e6-3246-4e0a-bbec-156dbd291e86.png)

This is when the plugin is enabled.

![image](https://user-images.githubusercontent.com/88898230/208212265-3028128d-ac63-4db3-9b1c-6d6f530dd6a0.png)

Thanks

**Comment by jp-cen** [comment]
You can disable mark sans inside of make.Md settings to get the markdown syntax back

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Liong1976 ***@***.***>
Sent: Friday, December 16, 2022 7:18:26 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Makemd makes the # symbol for headings disappear (Issue #18)


First, I would like to thank you for creating this fantastic plugin.

I am concerned that this plugin makes the symbol of # for headers disappear in LP when I put the cursor in the heading.

This is the screenshot when the plugin is disabled.

[image]<https://user-images.githubusercontent.com/88898230/208212222-e82435e6-3246-4e0a-bbec-156dbd291e86.png>

This is when the plugin is enabled.

[image]<https://user-images.githubusercontent.com/88898230/208212265-3028128d-ac63-4db3-9b1c-6d6f530dd6a0.png>

Thanks

**Comment by Liong1976** [comment]
Oh, thanks @jp-cen

**Comment by Andyspickle** [comment]
Hi @jp-cen. 

Is there a way to disable Mark Sans permanently? I am not sure if there is an issue with Obsidian Sync, but I keep having to disable Mark Sans because it keeps re-enabling itself

**Comment by jp-cen** [comment]
That’s strange, the setting is also default off so not sure why it would turn back on. Will be disabling mark sans in the next update for now to until the issue can be resolved.

**Comment by jp-cen** [comment]
Mark sans has been disabled and will be revisited in a future update with more stability
