### ISSUE TITLE
Turn off duplication of folders/notes between Spaces

### ISSUE THREAD

**Issue by PurpleViolentLocust** [Make-md/makemd#182]
**Background:** 

I have two Obsidian configs, one at work, and one at home, and only my configuration at home is doing this, so something is definitely wrong with my configuration, or bugged. I could not find anything in the Core or MAKE.MD plugin settings to toggle this setting. 

**Problem:** 

Creating a note or folder in one space will automatically create it in the other spaces. I do not want these unique spaces to contain the exact same notes, that defeats the purpose of having separate, unique spaces. 

**Example:**

![Screenshot 2023-08-18 at 8 47 11 AM](https://github.com/Make-md/makemd/assets/55510354/b47c8129-9ff3-41b1-a98d-2bb55c9719d9)

Screenshot shows "Lifey" Space at the top, with a Note "Stuff" and a folder "Trave". 

You can see in my "Labby" space this same folder/note structure exists. Why? 

**Steps to Reproduce:**
Creating any new folder or note in any space will automatically create that note or folder in the other space/s. 

**Acceptance:** 

Spaces should be separate, unique ecosystems that at the very least, do not AUTOMATICALLY duplicate one another. I know this is the way my Works Obsidian config works...but for some reason my Home config is working like this.

**Comment by jp-cen** [comment]
What's probably happening is that one of the Spaces is synced to a folder/vault and when adding a note to the other space, the note is stored in the default note folder which is the vault by default. Depends on what you would like the behavior to be, you have a few choices. Either you can change the default note folder for the Space to be one that's not your vault or you can remove the "default" vault Space since it will always contain all of the notes that are created

**Comment by PurpleViolentLocust** [comment]
> What's probably happening is that one of the Spaces is synced to a folder/vault and when adding a note to the other space, the note is stored in the default note folder which is the vault by default. Depends on what you would like the behavior to be, you have a few choices. Either you can change the default note folder for the Space to be one that's not your vault or you can remove the "default" vault Space since it will always contain all of the notes that are created

Ah, that was the issue. Thank you very much! That was driving me crazy.
