### ISSUE TITLE
Allow disabling the reminder of "Type '/' for commands"

### ISSUE THREAD

**Issue by wenlzhang** [Make-md/makemd#187]
This reminder in note editor is a bit disturbing to me. It would be great if one can remove the reminder text.

**Comment by jp-cen** [comment]
You can turn off the placeholder text in settings

**Comment by wenlzhang** [comment]
> You can turn off the placeholder text in settings

I am quite new to this plugin, and I have version 0.7.31. Can you be more specific about this? Which option can be used to turn off this?

**Comment by jp-cen** [comment]
It should be Flow Menu Hint Text

**Comment by wenlzhang** [comment]
Thanks! This works for me.
