### ISSUE TITLE
[Feature request] Hotkey or option to collapse all your spaces folders/subfolders

### ISSUE THREAD

**Issue by SHHSSH** [Make-md/makemd#195]
Hotkey or option to collapse all your Spaces' folders/subfolders.

So that your Show Folder Note by Default doesn't malfunction as to its scroll position. 
As sometimes Show Folder Note by Default isn't able to pinpoint the location/direction in the Spaces tab.

What I mean by this is that it doesn't autoscroll correctly to the opened note and if you've expanded too many folders, it becomes excessive and it doesn't pinpoint the opened note in the side bar.

**Comment by SHHSSH** [comment]
<a href="https://ibb.co/g9jSm03"><img src="https://i.ibb.co/8sKrNy0/capture-009-27092023-175358.png" alt="capture-009-27092023-175358" border="0"></a><br /><a target='_blank' href='https://dedupelist.com/'>combo duplicate remover</a><br />

**Comment by kenwarner** [comment]
There's a `Collapse All Folders` command already available.

**Comment by jp-cen** [comment]
In 0.8 (preview has been posted on discord for now), Spaces will be nestable, I’m a bit hesitant to add a Expand All Space since there is a scenario where you can have recursive nested spaces, but adding a expand top level spaces is certainly possible

**Comment by SHHSSH** [comment]
Thank you both.
