### ISSUE TITLE
Scrollbar in navigator pane

### ISSUE THREAD

**Issue by DutchPete** [Make-md/makemd#2]
With Make.md enabled you get 1 long, unusuable scrollbar.

![image](https://user-images.githubusercontent.com/10794265/202380309-c128a80b-06ef-44fc-bf4c-982bd366209a.png)

**Comment by jp-cen** [comment]
Trying to reproduce this. Which OS are you using?

**Comment by DutchPete** [comment]
MacOS

**Comment by jp-cen** [comment]
Good catch! Fix in next release

**Comment by jp-cen** [comment]
Added fix in 0.4.9

**Comment by DutchPete** [comment]
This issue has been fixed, it works, so I'll close it.
