### ISSUE TITLE
Menu Doc: "Files", "Search" and "Starred" Missing from the top left

### ISSUE THREAD

**Issue by scottrlarson** [Make-md/makemd#20]
Update to 1.1.8
Open and close application
those icons at the top left disappear.

**Comment by jp-cen** [comment]
I’m assuming this is related to the tabs being hidden. You can turn off the hiding by turning off the hide tab bar setting

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Scott Larson ***@***.***>
Sent: Wednesday, December 21, 2022 9:17:12 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Menu Doc: "Files", "Search" and " (Issue #20)

**Comment by scottrlarson** [comment]
The only option I see about tabs is the "Show Title Tab Bar" and that is enabled...

**Comment by jp-cen** [comment]
You need to goto the make.Md settings

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scottrlarson** [comment]
Ahh shoot. I found it, thanks.

**Comment by jp-cen** [comment]
Thanks, our documentation is still in development as we are adding more features. Currently it’s all in our discord. We will make it available on the web once its ready.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scottrlarson** [comment]
Sounds good. Awesome plug-in btw. Im finally able to sort the way I want to.

**Comment by jp-cen** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
