### ISSUE TITLE
Where have my custom spaces gone?

### ISSUE THREAD

**Issue by GiacomoLaw** [Make-md/makemd#200]
Just updated to the new version, and now all my custom spaces are gone and I can't seem to get them back. Does anyone know how I can get them back, or if I can use an older version of the plugin?

**Comment by MAWSpitau** [comment]
Same here - It realy sucks. AND  I can't find it to configure my smartspace back. Or at least a recursiv search throug folders.

**Comment by jp-cen** [comment]
Run the command Migrate Spaces from 0.7

**Comment by GiacomoLaw** [comment]
Thanks very much, worked.
