### ISSUE TITLE
Smart spaces do not save after creating and attempting to add more folders

### ISSUE THREAD

**Issue by GiacomoLaw** [Make-md/makemd#201]
Create a smart space. Add some folders. Edit the smart space to add more folders, cannot click save. Clicking the X or cancel adds no folder.

**Comment by jp-cen** [comment]
Thanks, I was able to reproduce it and will be patching it in the next patch today.

**Comment by GiacomoLaw** [comment]
Thanks very much

**Comment by jp-cen** [comment]
Fixed in 0.8.6

**Comment by GiacomoLaw** [comment]
Thanks so much.

Fixed 9fe488b00dbf01f57f9a1def0604b855f7451436
