### ISSUE TITLE
The sorting of the new Space Folder is very inconvenient.

### ISSUE THREAD

**Issue by alexinea** [Make-md/makemd#204]
The old version of Space Folder had very convenient sorting, and its performance was decent. However, the sorting performance of the new version is quite terrible, and the sorting experience is also poor. I suggest adding a sorting panel to address this issue, allowing for quick customization of the sorting of folders at the same level.

**Comment by jp-cen** [comment]
Thanks for the feedback, can you be more specific in terms of the experience being poor? Are you referring to the indicator style (a preview of the position instead of a line indicator), the accuracy being poor for certain items or etc.

**Comment by Phrown420** [comment]
I know what they mean about the performance. When dragging a file up and down the list every single time it passes another file it stops instead of instantly snapping to where your cursor is. This makes it seem like the file is lagging as it moves, and makes sorting way slower than it should be. The files really need to just jump to where your cursor is instead of "climbing" their way up.

**Comment by alexinea** [comment]
> I know what they mean about the performance. When dragging a file up and down the list every single time it passes another file it stops instead of instantly snapping to where your cursor is. This makes it seem like the file is lagging as it moves, and makes sorting way slower than it should be. The files really need to just jump to where your cursor is instead of "climbing" their way up.

Yes, that's what I wanted to provide feedback on. I'm not sure how to express it...

**Comment by jp-cen** [comment]
Will be looking into this in the coming week

**Comment by alexinea** [comment]
I noticed an interesting phenomenon. When I restarted Obsidian, the sorting performance improved significantly.

**Comment by alexinea** [comment]
This issue has been greatly improved thanks to the efforts of the development team.
