### ISSUE TITLE
SmartSpaces / migration and Option at all

### ISSUE THREAD

**Issue by MAWSpitau** [Make-md/makemd#205]
Hello, 

I am really disappointed with the last update. All my Smartspaces that I need in my professional environment are simply gone. The migration tool did not work (see screenshots).

And then the SmartSpaces option no longer seems to exist, with which I could reconfigure my lost settings. 

Is it somehow possible to define a folder as a Space that then also takes care of all the files in the subfolders? That might be a workaround. 

Greetings
MAW

 
![This is a SmartSpace after migration :(](https://github.com/Make-md/makemd/assets/539371/46f7014d-debd-4e09-abd0-dd687f589cd1)

**Comment by jp-cen** [comment]
This is what opens when you click Kuk in the Spaces panel? And Kuk is a Space and not a note (has the expanding icon on the left)?

**Comment by jp-cen** [comment]
The Smart Space config has been migrated properly based on the metadata, but you're opening the note that's associated with the Space rather than the Space it self based on the screenshot

**Comment by jp-cen** [comment]
Also, for smart spaces creation, all folders can now be a combination of a normal space and a smart space, you can add a Smart Search inside of the Edit Space modal to add smart search to any existing folder/space, this allows you more freedom in how spaces are defined.

**Comment by MAWSpitau** [comment]
Yes - I am in the Spaces-Area and this is what I get:
![grafik](https://github.com/Make-md/makemd/assets/539371/084594df-5f40-4cca-9742-5cb336492065)


May be I don't get it, but how do I get a SmartSpace showing me all entries with the property type=kuk all over my vault? It was sooo easy in the old version, but now I have like a Knot in my head to figure that out.

**Comment by MAWSpitau** [comment]
Hey, I was playing around  and now I got it. The usability is quite different form the last version. But now it works. Thanks for helping me.
