### ISSUE TITLE
How To Disable It this toolbar

### ISSUE THREAD

**Issue by paranjay245** [Make-md/makemd#21]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/120307516/209231076-808ae783-1510-4f2e-9177-94356e8c43c5.png">
I Got Editing Toolbar in My Vault & This Feature Overlaps Please Give Option To Disable It Else Everything Else is Perfect

**Comment by jp-cen** [comment]
Inline styler setting

**Comment by paranjay245** [comment]
wow thank you soo much i tried reloading plugin it didnt worked but after restarting obsidian it worked thank you soo much
