### ISSUE TITLE
[REQ] Setting to deactivate 'New Note' button and the 'Spaces' dropdown to save space

### ISSUE THREAD

**Issue by janpeeters70** [Make-md/makemd#22]
Thanks for developing Make. I'm following it with interest, and I can see some features becoming part of Obsidian in the future. 
For me, it would be great though if there would be a toggle in settings to deactivate 'New Note' button and 'Spaces' dropdown to save space in the left sidebar. I can easily create new notes with the context menu or a command, and the same counts for creating a new space. Currently, to my taste, they take up too much valuable space in the sidebar. Thanks for considering.

**Comment by jp-cen** [comment]
Collapsing the top section is currently planned, you can use CSS for now to hide it

**Comment by jp-cen** [comment]
Compact mode now addresses this
