### ISSUE TITLE
Restoring main Obsidian keyboard menu on mobile

### ISSUE THREAD

**Issue by martindkaz** [Make-md/makemd#228]
With the plugin enabled in the mobile app, the menu above the keyboard becomes as per this image:
![with plugin enabled](https://github.com/Make-md/makemd/assets/53477319/f1fba4fc-a773-45f3-9e3e-d3fa2c2b7027). Is it possible to restore or make default the original Obsidian menu as per this image: ![without plugin](https://github.com/Make-md/makemd/assets/53477319/26ecbc9a-f395-46c8-a9bd-68e951de97da)? I was not able to find an option in settings.
Thanks

**Comment by jp-cen** [comment]
Turn off Mobile styler inside settings and then restart the app

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Martin Dimkovski ***@***.***>
Sent: Saturday, November 25, 2023 1:08:27 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Restoring main Obsidian keyboard menu on mobile (Issue #228)


With the plugin enabled in the mobile app, the menu above the keyboard becomes as per this image:
with.plugin.enabled.jpg (view on web)<https://github.com/Make-md/makemd/assets/53477319/f1fba4fc-a773-45f3-9e3e-d3fa2c2b7027>. Is it possible to restore or make default the original Obsidian menu as per this image: without.plugin.jpg (view on web)<https://github.com/Make-md/makemd/assets/53477319/26ecbc9a-f395-46c8-a9bd-68e951de97da>?
Thanks

**Comment by martindkaz** [comment]
Thank you
