### ISSUE TITLE
BUG: Make.md breaks 'Files: Reveal current file in navigation' function of Obsidian

### ISSUE THREAD

**Issue by ianTevesAcc** [Make-md/makemd#242]
**ENVIRONMENT:**
        Windows 11 Home 
        Version 23H2
        OS build 22631.2792
**SYSTEM INFO:**
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Home 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 51
	Plugins enabled: 2
		1: MAKE.md v0.8.14
		2: Excalidraw v2.0.8

**Make.md breaks 'Files: Reveal current file in navigation' function of Obsidian**
The plugin makes it so when the command 'Files: Reveal current file in navigation' is run it no longer shows where the note is in the note explorer.

**To Reproduce**
1. Install and enable Make.md obsidian plug in
2. Open Obsidian
3. Press "ctrl + p" to open command input window
4. Search "Files: Reveal current file in navigation" and run it

**Expected behavior**
The current note location will be revealed in the File Explorer and is highlighted. 
But currently it takes the user to the Make.md Space Window without any action into showing the location of the current note/file being accessed.

**Screenshots**
![image](https://github.com/Make-md/makemd/assets/105651670/68177dc8-dfe0-437d-a4c3-bb0b58ca80c3)
Command to locate note in file explorer "Files: Reveal current file in navigation"

![image](https://github.com/Make-md/makemd/assets/105651670/08f2f4be-ca3c-4640-badb-dc692d5a9aac)
Bad Outcome: when command is run with Make.md plugin on (taken to Make.md Spaces window on the left without showing the location of the current note.

![image](https://github.com/Make-md/makemd/assets/105651670/abfec3b3-bb75-4fc8-8e10-56c3d096f00f)
Good Outcome: when command is run without Make.md plugin on (taken to the folder with the current note being accessed on the left and highlighted!)

**Additional Context**
Finding files quickly and organizing them on Obsidian is very important to me and which is why I even downloaded Make.md in the first place. Please help me in placing a fix for this issue 😓

**Comment by jp-cen** [comment]
You can turn on “Compatibility Mode” in settings if you want to continue using the File Explorer as your main explorer

**Comment by ianTevesAcc** [comment]
> You can turn on “Compatibility Mode” in settings if you want to continue using the File Explorer as your main explorer

Thank you! This worked 😁
