### ISSUE TITLE
Add support for stickers to non-Markdown files

### ISSUE THREAD

**Issue by alexinea** [Make-md/makemd#243]
For non-Markdown files, based on the current mechanism of MAKE.MD, it is not possible to change the Sticker settings. Currently, the mechanism of MAKE.MD involves writing custom icons in the frontmatter of Markdown files.

As for third-party plugins like DataLoom and built-in features like Canvas, their Stickers cannot be modified. Is it possible to write custom information for non-Markdown files inside the .space folder (with synchronized filename changes), so that custom information can be maximally compatible with third-party plugin files?

It's a pleasant surprise that Excalidraw supports modifying Stickers.

**Comment by jp-cen** [comment]
The rewrite of the storage and caching engine in the next version will fix this bug. Will be released soon.

**Comment by alexinea** [comment]
> The rewrite of the storage and caching engine in the next version will fix this bug. Will be released soon.

Good news. I'm really looking forward to it.

**Comment by jp-cen** [comment]
update is live

**Comment by alexinea** [comment]
Thanks to the efforts of the development team, this feature has been implemented!
