### ISSUE TITLE
Issues with "custom-sort plugin" and "file explorer note count plugin"

### ISSUE THREAD

**Issue by merlinuwe** [Make-md/makemd#25]
Thanks for your GREAT plugin! It surely has a BIG future!

Here are my issues:

![image](https://user-images.githubusercontent.com/4138869/209580893-9645c71e-3b72-479a-b85f-95b153961478.png)

- Failed to load plugin custom-sort
- Failed to load plugin file-explorer-note-count

If I deactivate make.md, these errors don't occure.

 
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.1.17
	Snippets enabled: 22
	Restricted mode: off
	Plugins installed: 60
	Plugins enabled: 46
		1: Vault Statistics v0.1.3
		2: Templater v1.16.0
		3: Tag Wrangler v0.5.5
		4: Tasks v1.20.0
		5: Symbols Prettifier v1.1.1
		6: Style Settings v0.4.12
		7: Sortable v0.2.6
		8: Scroll to Top Plugin v1.5.0
		9: Recent Files v1.3.5
		10: Paste image rename v1.5.0
		11: Pandoc Plugin v0.4.1
		12: Obsidian Enhancing Export v1.1.7
		13: Obsidian Camera v1.5.0
		14: Number Headings v1.10.0
		15: Minimal Theme Settings v6.1.1
		16: Media Extended v2.11.1
		17: Linter v1.10.1
		18: Janitor v1.0.7
		19: Homepage v2.6
		20: Find orphaned files and broken links v1.8.0
		21: File Tree Alternative Plugin v2.2.7
		22: Execute Code v1.5.0
		23: Excel to Markdown Table v0.4.0
		24: Editor Syntax Highlight v0.1.3
		25: Editing Toolbar v2.2.3
		26: Dataview v0.5.47
		27: Copy document as HTML v0.3.3
		28: Contextual Typography v2.2.4
		29: Completr v3.1.0
		30: Commander v0.4.9
		31: Calendar v1.5.10
		32: Buttons v0.4.19
		33: Auto Class v2.2.0
		34: Advanced URI v1.31.2
		35: Bulk Rename v0.4.4
		36: DB Folder v3.1.0
		37: Waypoint v1.4.0
		38: Folder Note v0.7.3
		39: Hover Editor v0.11.8
		40: Show Current File Path v0.5.2
		41: Reminder v1.1.15
		42: Text expand v0.11.2
		43: Icon Folder v1.5.1
		44: Excalidraw v1.8.7
		45: Custom File Explorer sorting v1.4.0
		46: File Explorer Note Count v1.2.0

**Comment by jp-cen** [comment]
Turn on use spaces along with file explorer or turn off use spaces in make.Md settings.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: merlinuwe ***@***.***>
Sent: Monday, December 26, 2022 3:19:49 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Issues with "custom-sort plugin" and "file explorer note count plugin" (Issue #25)


Thanks for your GREAT plugin! It surely has a BIG future!

Here are my issues:

[image]<https://user-images.githubusercontent.com/4138869/209580893-9645c71e-3b72-479a-b85f-95b153961478.png>

  *   Failed to load plugin custom-sort
  *   Failed to load plugin file-explorer-note-count

If I deactivate make.md, these errors don't occure.

SYSTEM INFO:
Obsidian version: v1.1.9
Installer version: v1.1.9
Operating system: Windows 10 Home 10.0.19045
Login status: not logged in
Insider build toggle: off
Live preview: off
Legacy editor: off
Base theme: dark
Community theme: Minimal v6.1.17
Snippets enabled: 22
Restricted mode: off
Plugins installed: 60
Plugins enabled: 46
1: Vault Statistics v0.1.3
2: Templater v1.16.0
3: Tag Wrangler v0.5.5
4: Tasks v1.20.0
5: Symbols Prettifier v1.1.1
6: Style Settings v0.4.12
7: Sortable v0.2.6
8: Scroll to Top Plugin v1.5.0
9: Recent Files v1.3.5
10: Paste image rename v1.5.0
11: Pandoc Plugin v0.4.1
12: Obsidian Enhancing Export v1.1.7
13: Obsidian Camera v1.5.0
14: Number Headings v1.10.0
15: Minimal Theme Settings v6.1.1
16: Media Extended v2.11.1
17: Linter v1.10.1
18: Janitor v1.0.7
19: Homepage v2.6
20: Find orphaned files and broken links v1.8.0
21: File Tree Alternative Plugin v2.2.7
22: Execute Code v1.5.0
23: Excel to Markdown Table v0.4.0
24: Editor Syntax Highlight v0.1.3
25: Editing Toolbar v2.2.3
26: Dataview v0.5.47
27: Copy document as HTML v0.3.3
28: Contextual Typography v2.2.4
29: Completr v3.1.0
30: Commander v0.4.9
31: Calendar v1.5.10
32: Buttons v0.4.19
33: Auto Class v2.2.0
34: Advanced URI v1.31.2
35: Bulk Rename v0.4.4
36: DB Folder v3.1.0
37: Waypoint v1.4.0
38: Folder Note v0.7.3
39: Hover Editor v0.11.8
40: Show Current File Path v0.5.2
41: Reminder v1.1.15
42: Text expand v0.11.2
43: Icon Folder v1.5.1
44: Excalidraw v1.8.7
45: Custom File Explorer sorting v1.4.0
46: File Explorer Note Count v1.2.0

**Comment by merlinuwe** [comment]
Oh, knowing how to read is one of the greatest qualifications one can get ...

Thank you for the fastest response ever that helped immediately!

**Comment by Sacro** [comment]
Sorry, I don't see this option available, has it been removed?

**Comment by chaetal** [comment]
I don't see the option either. Please, update the information here.
