### ISSUE TITLE
Moving Item / Note to a different Space/Folder through "right-click menu" makes the note unreadable

### ISSUE THREAD

**Issue by Lumichi** [Make-md/makemd#279]
Basically:
Currently, it is in versions 08.15 and above

1. make make a note
2. make a folder (skip if already have  a folder)
3. right click the note
4. find the move file to
5. find the folder / any folder and move the note/any note to that folder

Expected Result:
1. Moves file normally to that selected folder without issues

Actual Result:
1. Moves file to that selected folder but it makes it unreadable, to be more specific, it removes the .md extension of the note for some reason, so I have to edit the file manually and add the missing .md extension

Bonus Problem:
No choices of moving folders through the right click menu, I always need to drag it. But I do not usually use the option to drag because it is a bit finicky and I usually misplace it on some other adjacent folders

**Comment by jp-cen** [comment]
Thanks for catching this, this will be fixed in the release that’s being prepared for release right now.

**Comment by jp-cen** [comment]
Fixed in 0.9
