### ISSUE TITLE
Error in reveal current file in navigation

### ISSUE THREAD

**Issue by AndyJZhao** [Make-md/makemd#28]
Thanks for the great plugin! I sincerely appreciate your effort.
Obsidian has an option of navigating to the current file in the navigation named: "Files: Reveal current file in navigation". This could very beneficial when you have multiple nested folders.
However, after installing Makemd, while pressing the hotkey of "Files: Reveal current file in navigation", the file explorer navigates to the "Spaces" pane instead of the "Files" pane and shows the current file. 
Please kindly fix this bug.

**Comment by jp-cen** [comment]
Thanks! You need to turn on "Use Spaces along with File Explorer" in order for Spaces not to override any file explorer commands.

**Comment by liquiddandruff** [comment]
I'm getting the same issue here.

When I CTRL+P and action ""Files: Reveal current file in navigation" it just takes me to the Spaces view and nothing is highlighted.

Has this "Use Spaces along with File Explorer" option been removed? I don't see it in the MAKE.md settings page.

I see "Reveal Active File" but toggling it on / off doesn't seem to do what it says on the tin: when I'm in the spaces view, nothing is highlighted when switching between active panes. Let me know if i'm doing something wrong--thank you!

**Comment by srizzo** [comment]
I'm facing the same issue. Can't find Use Spaces along with File Explorer either.
