### ISSUE TITLE
New Note Place Holder Problem

### ISSUE THREAD

**Issue by Lumichi** [Make-md/makemd#284]
So, when I was trying to make a new note using the my hotkey CTRL+N, the note was titled as "Untitled" even though I set it Up as "UNSORTED" at first. 
My current version is: 0.9.3
but I went back to test as far as version 0.8.14

To recreate: 
1. set a custom folder where new notes are placed
2. go to make.md settings and change the New Note Placeholder to whatever you want
3. New note using CTRL+N or the + 

Expected:
1. New note should be entitled as what you set it to be (e.g. Unsorted)

Actual:
1. New note was named as "Untitled" and not Unsorted

**Comment by jp-cen** [comment]
Will be fixed in today's patch

**Comment by Lumichi** [comment]
> Will be fixed in today's patch

[current make.md version = 0.9.5] 
[current obsidian version = 1.5.8] 
hello hello, Just found out today, that apparently, the new note placeholder is still broken, well kind of.
The New Note placeholder works as intended when pressing on the New note button manually (the plus button at the side of the folder/space) but If I use the Default shortcut which is "Ctrl + N," it will not work and the new note will remain as "Untitled"

**Comment by Lumichi** [comment]
[current make.md version = 0.9.5] 
[current obsidian version = 1.5.8] 
hello hello, Just found out today, that apparently, the new note placeholder is still broken, well kind of.
The New Note placeholder works as intended when pressing on the New note button manually (the plus button at the side of the folder/space) but If I use the Default shortcut which is "Ctrl + N," it will not work and the new note will remain as "Untitled"
