### ISSUE TITLE
[Feature Request] Table view multi-option type column should have different styling for an option

### ISSUE THREAD

**Issue by Runecreed** [Make-md/makemd#289]
Hi

I'm attempting to color the different options available in my Spaces List View Table where there's a column of type 'Option' with multiple options toggled on

something like this:

![image](https://github.com/Make-md/makemd/assets/9799758/62198361-b683-4514-9acd-666bae365273)

where i'd love to have the 'high' / 'low'  / 'mid' values highlighted in red, blue and yellow, for example.

However im not having much luck - i've tried wrapping the option value with a <div> and adding css styling to that, but that didnt work either

I tried the same in a Context element - still no luck, except curiously i was able to get the coloring to display on a Card View - but that's not a proper format for my use case, specifically looking for the List View

The reason I want this is to be able to identify an option that i'll be using in multiple rows, quickly and easily - if they can be colored its much easier to identify them in the sequence.

**Comment by Runecreed** [comment]
Coming from Notion this was a very convenient feature and im trying to replicate it

![image](https://github.com/Make-md/makemd/assets/9799758/890fa68a-ef5d-4a7b-b387-ca743cb9982f)

**Comment by jp-cen** [comment]
This was added recently in 0.9.17
