### ISSUE TITLE
When I click on the folder, an error page will be displayed.

### ISSUE THREAD

**Issue by PrinSoul** [Make-md/makemd#305]
When I click on the folder, an error page will be displayed. How can I solve it? Reinstalling is useless.
![error page](https://github.com/Make-md/makemd/assets/4762388/ac7c07f7-0a00-4973-b576-7f24d1b6cc2e)

**Comment by jp-cen** [comment]
Can you send me the full error in the developer console (Control-Shift-I) on Windows or (Command-Option-I) on Mac to show. Thanks!

**Comment by PrinSoul** [comment]
> Can you send me the full error in the developer console (Control-Shift-I) on Windows or (Command-Option-I) on Mac to show. Thanks!
![error in the developer console](https://github.com/Make-md/makemd/assets/4762388/8bda832b-fe66-4a68-a74b-45208701878e)

**Comment by jp-cen** [comment]
Can you let me know the name of the plug-in you're using that starts with loca and ends with mages-plus. I'm assuming its local something images-plus

**Comment by PrinSoul** [comment]
> Can you let me know the name of the plug-in you're using that starts with loca and ends with mages-plus. I'm assuming its local something images-plus

plugin:obsidian-local-images-plus

**Comment by PrinSoul** [comment]
> Can you let me know the name of the plug-in you're using that starts with loca and ends with mages-plus. I'm assuming its local something images-plus


I just closed local-images-plus and restarted obsidian, restarted it, and now it can be used normally, thx

**Comment by jp-cen** [comment]
Thanks for the info, I'll follow up once I find out how this conflict can be prevented.

**Comment by jp-cen** [comment]
I've included a fix in the next patch.

**Comment by PrinSoul** [comment]
> I've included a fix in the next patch.

thx, I have a question. Can the current plug-in allow different folders to apply corresponding css file styles?

**Comment by jp-cen** [comment]
There's no customization with the CSS directly. You can however, indirectly apply styling to a note through the space view (also referred to as folder note). It's not as flexible as CSS as you can only modify the tokens instead of selectors.

**Comment by PrinSoul** [comment]
> There's no customization with the CSS directly. You can however, indirectly apply styling to a note through the space view (also referred to as folder note). It's not as flexible as CSS as you can only modify the tokens instead of selectors.

ok,thx your answer.
