### ISSUE TITLE
parseDate function of formula  is not working properly

### ISSUE THREAD

**Issue by JohanRain** [Make-md/makemd#307]
In fact, timestamp information can be obtained normally through prop('File')['metadata']['file ']['ctime'], but parseDate function cannot convert information correctly.

**Comment by JohanRain** [comment]
I have checked the source code and it is possible that formatDate(prop('File')['metadata']['file']['ctime']) should be the correct default value.

**Comment by jp-cen** [comment]
Formatdate gets automatically applied with the default date format so it’s not required. What are you trying to parse? The default created time value doesn’t need to be parsed because it’s already a date time object and just needs to be formatted

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JohanRain** [comment]
When creating a folder, the default Created property is as follows:
![image](https://github.com/Make-md/makemd/assets/87157569/8a1048fb-7b3f-4fd7-a0fa-43f16b01e370)
This date cannot be displayed correctly
I thought it was a problem with the parseDate function,But I found a formatDate function, so I think the default value should be using the wrong function, like the one below:
![image](https://github.com/Make-md/makemd/assets/87157569/c0d7bcbd-8034-460e-8ff0-5a8ab2fd920b)
The value of prop('File')['metadata']['file']['ctime'] is as follows:
![image](https://github.com/Make-md/makemd/assets/87157569/c8acd591-1d16-4fcf-ba7e-73f70fdfecce)

**Comment by jp-cen** [comment]
Thanks. Will look into it today. The formatDate chains a parse date in front of it if the data is a timestamp or string and parse date applies a format date if the final value is not formatted

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jp-cen** [comment]
Thanks for reporting this, this is confirmed to be an issue and will be patched next version.

**Comment by jp-cen** [comment]
Patched in 0.9.17
