### ISSUE TITLE
When I click on a folder that has sub-folders inside of them, it doesn't show up as a list

### ISSUE THREAD

**Issue by shihabshahriyar** [Make-md/makemd#308]
Before the last update, everything worked fine.

However, now, with some of the folders that have sub-folders in them, when I click on that folder, no subfolder list is displayed (unless I click on Select Space and select the correct folder manually)

<img width="1173" alt="Screenshot 2024-04-24 at 4 57 30 AM" src="https://github.com/Make-md/makemd/assets/20608014/e636891f-4795-47bd-9fad-aef647bb4c50">

Here's an example of a selected folder that displays subfolders properly: 
<img width="551" alt="Screenshot 2024-04-24 at 4 59 58 AM" src="https://github.com/Make-md/makemd/assets/20608014/7f1b85ba-a22e-49ff-aa9e-9226bd0d2738">

**Comment by jp-cen** [comment]
This looks like that folder is still on the 0.8 schema. You can either run the migrate from 0.8 command or relink them manually

**Comment by jp-cen** [comment]
Running the command will relink all your folders to the new schema.

**Comment by shihabshahriyar** [comment]
Could you please give a step by step guide on how to do this? I'm not sure what 0.8 schema or "relinking" means in the context of Make.MD

**Comment by jp-cen** [comment]
You can use control-P on windows or command-p on mac to open the command prompt and then type in migrate from 0.8. The view that's having issues for you was updated and previous customization you did is not compatible with the 0.9 build of make.md. The migration tool helps you convert all the customizations from 0.8 to 0.9

**Comment by shihabshahriyar** [comment]
Gotcha, I think it works now! Is there a list of additional things I need to do like this, that I might need to do to make Made.MD work without hiccups?

**Comment by jp-cen** [comment]
There were a lot of changes in 0.8 and 0.9 in order to make the system scalable and reliable in the long run so unfortunately there were some breaking changes that were introduced. The data structure changes have been finalized so there shouldn't be any moving forward and if there are any, we will be adding proper migrations.

 Right now, we're working on the stable 1.0 release, you may still see some bugs and unpolished feature as we finish, please report any that you see.

**Comment by shihabshahriyar** [comment]
Realy love the plugin though. it is one of the big reasons why I was able to shift from Notion to Obsidian, looking forward to a stable release!
