### ISSUE TITLE
Placing tables in a note does not work

### ISSUE THREAD

**Issue by viktoracevedo** [Make-md/makemd#318]
While inside a note, when you type the "/" key and choose the option to create a table, it creates a blank box with the options of search for element, display mode, options such as grouping and sorting, but you cannot see the table nor write on it.
Also when in read-only mode the note only appears "![![test folder/#^Table2]]"
Editing mode:
![1](https://github.com/Make-md/makemd/assets/53798899/06231b14-b73e-4a3e-8340-83a99cf0697f)
Reading mode:
![2](https://github.com/Make-md/makemd/assets/53798899/991e8227-84ce-4f83-ab36-ebfa2d7c3563)

**Comment by jp-cen** [comment]
Thanks for reporting this, these issues are being addressed very soon

**Comment by jp-cen** [comment]
Fixed in latest patch
