### ISSUE TITLE
Unhide folders in spaces

### ISSUE THREAD

**Issue by dlettie** [Make-md/makemd#319]
I recently opened a parent folder in a space, and then hid a child folder. How do I unhide that child folder?

**Comment by jp-cen** [comment]
In the main menu, there's a Manage Hidden Files option

**Comment by dlettie** [comment]
Thank you!

**Comment by aseyedia** [comment]
> In the main menu, there's a Manage Hidden Files option

Which main menu? Where is the Manage Hidden Files option?

**Comment by jp-cen** [comment]
Top of the sidebar with your vault name

**Comment by aseyedia** [comment]
![image](https://github.com/Make-md/makemd/assets/43455034/be4747f8-97e4-4008-9346-7a7100b91ffa)

I was just about to update my comment. Thank you!
