### ISSUE TITLE
Ampersand (`&`) displayed as `&amp;` in note titles

### ISSUE THREAD

**Issue by stephen-netu** [Make-md/makemd#320]
**Description:**
When using the Make.md plugin, note titles containing the ampersand (`&`) character are displayed as `&amp;`. Disabling the plugin resolves the issue.

**Steps to Reproduce:**
1. Install and enable the Make.md plugin.
2. Create or rename a note with an ampersand in the title (e.g., `Summit & Tower`).
3. Observe that the note title is displayed as `Summit &amp; Tower`.

**Expected Behavior:**
The note title should display as `Summit & Tower`.

**Environment:**
- Obsidian version: 1.5.12
- Make.md plugin version: 0.9.19
- Operating System: Windows 10

**Additional Context:**
Disabling the Make.md plugin resolves the issue, and the note title displays correctly.

**Screenshots:**
![image](https://github.com/Make-md/makemd/assets/12437943/e85fc23a-12cb-45cb-97a3-96b57bd47bcc)

Thank you for your help!

**Comment by jp-cen** [comment]
Thanks for catching this, the fix is in the next patch

**Comment by jp-cen** [comment]
Fixed and patched, thanks for reporting

**Comment by stephen-netu** [comment]
Thank you so much!  You are amazing!
