### ISSUE TITLE
High CPU consumption after last update

### ISSUE THREAD

**Issue by lifehaschanged** [Make-md/makemd#321]
Hi, 
the latest update is causing a constant increase in CPU usage, even long after it was activated.
It is not due to other plugins. Even when I disable all settings within the make.md settings, the CPU usage remains consistently high.
Has anyone else the same problem after the last update?

**Comment by jp-cen** [comment]
Thanks, I'm prioritizing these performance issues. How many notes do you have?

**Comment by jp-cen** [comment]
I have a good idea of where the issue is coming from, but some debug information would be helpful, for example, are you using smart/live search and formula properties?

**Comment by jp-cen** [comment]
There's a fix in the next version that should address the CPU issue

**Comment by jp-cen** [comment]
Let me know if this is resolved in the newest version
