### ISSUE TITLE
Can't Unhide note

### ISSUE THREAD

**Issue by Eusorph** [Make-md/makemd#324]
After I have hidden a note, I can't unhide it anymore. I couldn't find any documentation regarding this function either. Hidden note doesn't even show in the Context items menu.

**Comment by jp-cen** [comment]
You can manage your hidden files in the manage hidden files under the main menu

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Eusorph ***@***.***>
Sent: Wednesday, May 29, 2024 7:48:59 AM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Can't Unhide note (Issue #324)


After I have hidden a note, I can't unhide it anymore. I couldn't find any documentation regarding this function either. Hidden note doesn't even show in the Context items menu.

**Comment by reel-9** [comment]
What main menu?

**Comment by reel-9** [comment]
Nevermind, found it. 
According to the principle of direct manipulation, user should be able to reverse the action he/she did at the same place.
