### ISSUE TITLE
Problems with properties

### ISSUE THREAD

**Issue by Eusorph** [Make-md/makemd#326]
In Context/Folder view:

-Yes/No properties doesn't render Yes/No button in Table view if is marked in the properties of the actual note.
-Option property renders properties, but when a filter for said property is applied with "is", selector doesn't show the options, so it can't filter anything.

**Comment by jp-cen** [comment]
Please confirm that this is still happening after the properties update (0.9.26)

**Comment by Eusorph** [comment]
Now it work. Thanks :-)
