### ISSUE TITLE
Editing Embedded Notes not working

### ISSUE THREAD

**Issue by pokEarl** [Make-md/makemd#330]
Hey, I have just started using Obsidian and pretty sure all my settings are default. When I try to click the flow toggle sometmes nothing happens or it opens up the menu bar on the embed link to like make it bold. Sometimes it adds a !, but none of this behaviour has ever led me to be able to edit the embeds. 

Side question but this should work in the canvas as well, right? I've tried using it in notes also but my main purpose here is for canvas

I'm not sure what the icon is supposed to mean. If i look next to the embedded section there is a pen which says embed flow. But if i like highlight at the top where the embed link is the embedded text disappears and the toggle flow icon is now a book and the text dissappears. 8(

Okay I disabled all the non flow related settings and it seems to sort of work outside of the Canvas but does now work in the canvas :{

But yeah been clicking around and trying random things for a while now nothing has allowed me to edit my embedded sections. 

<img width="822" alt="image" src="https://github.com/Make-md/makemd/assets/12936425/5e2cce3e-9b56-4038-b428-95a4b1d15631">

<img width="846" alt="image" src="https://github.com/Make-md/makemd/assets/12936425/04190acb-7e51-41ee-84c4-58405e7b633c">

**Comment by jp-cen** [comment]
Patched in latest version
