### ISSUE TITLE
Issues with the "Make a Copy" function in Space view

### ISSUE THREAD

**Issue by turboyac** [Make-md/makemd#331]
I'm always in Space view ever since I discovered Make.md, which I love. However while in the Space UI, "Make a copy" of a file doesn't always work. When it does, the duplicate takes 5 seconds or more to appear, but also appears inside a newly created folder. 

Is there a way to make it instant and without a folder just like when duplicating a file Obsidian? When using "make a copy" in Obsidian UI, the duplicate file appears instantly below the original with an incremental number.

**Comment by jp-cen** [comment]
Patched in latest version

**Comment by turboyac** [comment]
Fantastic! Thanks so much
