### ISSUE TITLE
[BUG] - adding a callout item to a space view breaks space view and throws error

### ISSUE THREAD

**Issue by jurgen-vk** [Make-md/makemd#333]
when adding a callout item in the space view, it throws the following error:

`Cannot read properties of undefined (reading 'length')`

there is no way of repairing this for users besides throwing away the views.mdb file inside the .space folder.

**Comment by jp-cen** [comment]
Thanks for reporting this, this will be prioritized for the next version.

**Comment by jp-cen** [comment]
Patched in latest version
