### ISSUE TITLE
dates do not work for previous years

### ISSUE THREAD

**Issue by jacobaclarke** [Make-md/makemd#34]
When I have a metadata field like "date" that is "2020-02-01" it will label the date as "2023-02-01" in the table on the flow view. How can I fix this?

**Comment by jp-cen** [comment]
It says 2023-02-01 or is it missing the year? Year is missing in the date format, will be adding it

**Comment by jacobaclarke** [comment]
Yep, it is missing the year. When I try to update the date, thee date picker defaults to 2023. I was trying to find a way to make a pull request but can't seem to be able to build. Do you have contributor guidelines?

**Comment by jp-cen** [comment]
Currently refactoring before merging the latest source code.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jp-cen** [comment]
fixed in latest version
