### ISSUE TITLE
Requirements for open-source plugins are not met

### ISSUE THREAD

**Issue by joethei** [Make-md/makemd#342]
Hi @jp-cen,

We noticed that you continue to release new versions of your plugin, yet the source files in the repo are not being updated.

If you intend for your plugin to be open source, the following conditions need to be met:
- The source files need to be uploaded, so that one can build the current version of the `main.js` from it.

If you intend for your plugin to be closed source the following conditions need to be met:
- Add the text "(Closed source)" to the end of the plugin description.
- Provide the Obsidian team with access to the source code. You can do this by giving me access to the repo.
- Remove the MIT license from the project.

If these requirements are not met within 30 days, this plugin will be removed from the community directory.

Thanks,
— The Obsidian team

**Comment by jp-cen** [comment]
The code was being rewritten and has now been updated with the latest release. Thanks!
