### ISSUE TITLE
Custom Folder Note Filename

### ISSUE THREAD

**Issue by octo-kumo** [Make-md/makemd#347]
Currently folder notes are named the same as the folder itself.

I want to use `index.md` for folder note instead, and hence would like to have a function added that allows customization of folder note filename thanks.

**Comment by jp-cen** [comment]
Added in latest patch

**Comment by octo-kumo** [comment]
When I click on the folder, it doesn't open index.md, instead it shows "New Note for index.md".
And when I click on that, it will create a new file `index 1.md`

**Comment by octo-kumo** [comment]
Furthermore, when I change folder name, a new note `folder-name.md` is created

**Comment by jp-cen** [comment]
This has now been resolved properly in the latest patch, thanks for testing
