### ISSUE TITLE
Tables broken in Version 0.9.999

### ISSUE THREAD

**Issue by PJC-64** [Make-md/makemd#353]
I have a simple note with some text followed by a make-md table.  This has always worked with no problems, but as of Version 0.9.999 whenever I open that note (or try to add a table to a blank note), a new note 'undefined' or 'undefined x' where there are multiple of these.

Since I can't see the table contents (it's not in the '.md' file when I open it in an external code editor), until this is fixed all that data is inaccessible, and it's not possible to add new data either.

**Comment by jp-cen** [comment]
Thanks for reporting this, this has been hot fixed
