### ISSUE TITLE
Use the tabs in the Folder Context view to switch different views of files instead of (or in addition to) tables.

### ISSUE THREAD

**Issue by charle36** [Make-md/makemd#36]
Simple tables are great, but I feel like it would be more practical to be able to quickly switch from one saved view of the folder's files to another. 

In my workflow, simple tables are used for brainstorming more than anything, so I have little use for them in the Folder Context view. I do, however, use filters and the different viewing modes (table, list...) a lot, so the possibility to quickly switch from one to another would be very useful. 

Thanks!

**Comment by jp-cen** [comment]
You can save filters and sorts to Views which can be switched through the Files dropdown (which appears when you have more than 1 view). The UX will be improved in an upcoming update, for example there’s no way to delete or rename views.

**Comment by charle36** [comment]
Yeah, you can switch that way, but  I think it would be more practical to switch with the tabs instead.

**Comment by jp-cen** [comment]
One consideration is to change the direction. Different tables in the drop down and the different views across. Will consolidate the feedback from the discussion in discord and then update this thread. Potentially have it as a setting if there’s good case for both.

**Comment by charle36** [comment]
Awesome, thanks!
