### ISSUE TITLE
Make.md broke down after updating and nothing changed despite reinstalling and restarting obsidian / laptop

### ISSUE THREAD

**Issue by erinhysh** [Make-md/makemd#360]
I'm not even sure how to describe it, but the left side of obsidian is absolutely broken. I thought it was a theme thing but no matter what theme i use, it still looks like that

https://media.discordapp.net/attachments/983221434782466098/1277525587879133224/image.png?ex=66cd7beb&is=66cc2a6b&hm=8861fee185351c72f2b89d6bd21486767fb58a8e433c0a795138ba176b02dba4&=&format=webp&quality=lossless&width=1190&height=669

https://media.discordapp.net/attachments/983221434782466098/1277532085489369088/image.png?ex=66cd81f8&is=66cc3078&hm=64b839073240b24c4fae1d6f11f8940ea72afb7e2fb0a2aa8a3704db4ae7a7a0&=&format=webp&quality=lossless&width=348&height=668

**Comment by jp-cen** [comment]
Or you can manually download the stylesheet from this repo and replace it (reinstalling will reset some settings, but space configurations will not be reset)

**Comment by erinhysh** [comment]
oh nice it's fixed now! thank you very much
