### ISSUE TITLE
[BUG] tag filters don't work

### ISSUE THREAD

**Issue by Pesssimist** [Make-md/makemd#365]
When trying to create a tag filter in table view, the result is empty.
How did I get it:
1. Clean installation of the plugin version 0.9.1007 on the PC version obsidian 1.6.7.
2. A folder has been created in space.
3. Several notes have been created in the folder.
4. The table display is selected in the space.
5. The tags property has been added to the table and 1 tag has been added for each note (for each note its own).
6. In the view filter, filter by tag is selected, an existing tag is entered, as a result, it is empty.

It repeats every time.
Tag grouping also does not work correctly
![first](https://github.com/user-attachments/assets/fafa7399-679c-4953-8b7f-b32ec33eb4f8)
![second](https://github.com/user-attachments/assets/d06ed9dd-584a-45ba-8823-dee46a99e9bd)

**Comment by alexeydemidovkz** [comment]
Same for me, no matter how I tried. I reinstalled everything, deleted all files, and tried in different vaults — the result was the same. Thank you very much!

**Comment by jp-cen** [comment]
This is now patched

**Comment by Arhidiz** [comment]
> This is now patched

Unfortunately, it's not cured. The result is the same. 

<img width="898" alt="image" src="https://github.com/user-attachments/assets/c9ce1813-3eb3-46b9-a74a-573e1def2b82">

**Comment by alexeydemidovkz** [comment]
> This is now patched

no its not, i have a latest version of everything, tried the new vault too. It can filter/sort/group other fields but not tags

**Comment by alexeydemidovkz** [comment]
Installed 0.9.1010, all works now, thank you very much and please have a wonderful day!
