### ISSUE TITLE
[bug] The file and folder names cannot be the same

### ISSUE THREAD

**Issue by Scuffle-man** [Make-md/makemd#374]
I would like to report a bug.
<img width="137" alt="666" src="https://github.com/user-attachments/assets/1a53dea8-cce5-466d-beec-4f6b4ef91a9a">
The file and folder names cannot be the same, and if they are the same, the file will not be displayed.
like this
![image](https://github.com/user-attachments/assets/0ca4fee3-71c4-487a-b390-1a5a6d7ee634)

**Comment by Scuffle-man** [comment]
I found that the solution had to be uppercase and lowercase,but we can't keep using this method

**Comment by jp-cen** [comment]
The merging of the folder and note of the same name is the folder notes feature, which you can turn off in settings

**Comment by Scuffle-man** [comment]
![image](https://github.com/user-attachments/assets/ded6be95-18e0-4a5e-b38e-e7887da089b4)
It seems that this function is not bad, meaning that I can change this annotation to other names, is it like a picture, but after the modification, I still do n’t display my file. Is it my modification method wrong?

**Comment by Scuffle-man** [comment]
Thank you so much. It looks like this feature is pretty good,I can change the annotation to something else, isn't it like an image, but after changing it, I still don't show my file. Is my modification method wrong?
![376009245-ded6be95-18e0-4a5e-b38e-e7887da089b4](https://github.com/user-attachments/assets/331f0534-49e1-45bb-8914-db1f5ce0397f)

**Comment by jp-cen** [comment]
Try restarting obsidian to trigger a reindex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Scuffle-man** [comment]
Thank you very much, I followed your method, restarted the function, restarted the plugin, restarted the software, and it finally succeeded. It's a good feature, I won't use it, and I still need to learn the plugin feature
![image](https://github.com/user-attachments/assets/62a47b75-f1dc-41cb-93e3-00e639155629)
![image](https://github.com/user-attachments/assets/3cdda586-1e79-4575-8873-2b7a2a2c57b8)
