### ISSUE TITLE
Display hiden spaces

### ISSUE THREAD

**Issue by lexuna** [Make-md/makemd#380]
I accidentally clicked "Hide" at an important space. Now it's gone and I can't get it back. I searched for a while but couldn't find anything about it.

**Comment by jp-cen** [comment]
Use the Manage hidden files and folders in the main menu in the sidebar
________________________________
De : lexuna ***@***.***>
Envoyé : Monday, October 21, 2024 2:04:53 PM
À : Make-md/makemd ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [Make-md/makemd] Display hiden spaces (Issue #380)


I accidentally clicked "Hide" at an important space. Now it's gone and I can't get it back. I searched for a while but couldn't find anything about it.

**Comment by lexuna** [comment]
Do you mean in Files and links the excluded files? Its empty 
![image](https://github.com/user-attachments/assets/ac076b83-0266-4f7f-ae96-a9c2c5dcb3aa)

**Comment by jp-cen** [comment]
In the make.md navigator there’s a sidebar with the name of your vault at the top which you can use to access the main settings
________________________________
De : lexuna ***@***.***>
Envoyé : Monday, October 21, 2024 4:09:47 PM
À : Make-md/makemd ***@***.***>
Cc : JPC ***@***.***>; Comment ***@***.***>
Objet : Re: [Make-md/makemd] Display hiden spaces (Issue #380)


Do you mean in Files and links the excluded files? Its empty
image.png (view on web)<https://github.com/user-attachments/assets/ac076b83-0266-4f7f-ae96-a9c2c5dcb3aa>

**Comment by lexuna** [comment]
Found it, thank you.
