### ISSUE TITLE
Type `/` for commands

### ISSUE THREAD

**Issue by DutchPete** [Make-md/makemd#4]
Any chance of hiding this command comment? I don't use it and it irritates me.

**Comment by andremeireles** [comment]
You can open the **data.json** file in `VAULTNAME/.obsidian/plugins/maker-md` and change

`"menuTriggerChar": "/",`
to
`"menuTriggerChar": "",`

**Comment by jp-cen** [comment]
Setting for both
1. Changing trigger character
2. Hiding placeholder text
will be added in the next update.

**Comment by DutchPete** [comment]
@andremeireles thanks, did that, reloaded Obsidian, but `Type '/' for commands` still gets displayed.

**Comment by jp-cen** [comment]
No, that setting doesn't affect the placeholder

**Comment by DutchPete** [comment]
So, what does it affect?

**Comment by jp-cen** [comment]
The command trigger character (default is /)

**Comment by DutchPete** [comment]
OK, so I'll wait for the next update for “Hiding placeholder text will be added in the next update”.

**Comment by jp-cen** [comment]
Right now it's turned off when you turn off Maker Mode, but will add the setting as well.

**Comment by DutchPete** [comment]
Thank you. I won't use the maker mode anymore, so I personally don't need an extra setting.

**Comment by DutchPete** [comment]
This things is back in 0.4.9. I looked through the settings, I have only 2 things enabled:

- Spaces
- Flow Editor, which I have set to *seamless*.

I have disabled core plug-in **slash commands**.
Please advise.

**Comment by jp-cen** [comment]
The setting "Make Menu Hint Text" was added and has defaulted to on. You can turn it off to get rid of it. We've stabilized the settings names but in doing so changed many of them which will have reset some of the existing settings.

**Comment by DutchPete** [comment]
Like I said, I only have 2 settings enabled, and “Make Menu Hint Text” was disabled.
After reloading Make.md it does not show anymore.
Thanks for the hint.

**Comment by jp-cen** [comment]
Great! Will make settings reset without restart in an upcoming version.
