### ISSUE TITLE
Ability To Backup Spaces

### ISSUE THREAD

**Issue by grassbl8d** [Make-md/makemd#42]
Hello,

Would like to request a facility to backup spaces.

I get some behavior where I turned on Sync for the Community Plugins, The spaces are overriden and it would be refreshed to initial state due to syncing. I had to turn off the Community plugin sync in order for the Spaces.mdb to be each own copy.

It would be a nice feature to have to have backup for the state of a particular Spaces.mdb file.

As a workaround, I create a backup of the Spaces.mdb file and put them into an Obsidian folder which will be synced up. I overwrtie the folder with that file so that I can resume work on another workstation.

Thank You,

**Comment by jp-cen** [comment]
There is work being done right now to alleviate the issues around sync overwriting spaces. Back-up in settings could be a good idea and will consider adding it as well. Thanks for the feedback!

**Comment by maximberezin97** [comment]
I would LOVE to have the ability to backup, transfer, and restore spaces settings, particularly stickers and custom ordering!

**Comment by jp-cen** [comment]
Available in 0.7
