### ISSUE TITLE
I don't get the newest update (0.6.14)

### ISSUE THREAD

**Issue by Liong1976** [Make-md/makemd#52]
I don't get the newest update even though I clicked the `update` button.

![image](https://user-images.githubusercontent.com/88898230/218286553-109c0a51-4166-4643-af9d-6c7e4bc450a1.png)

OS: Windows
Obsidian version: 1.1.12, Installer: 1.1.9

**Comment by jp-cen** [comment]
There’s a caching issue with the GitHub edge servers in some regions. Seems to be widespread across other plug-ins as well. Looking into a solution or waiting for GitHub to resolve this issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Liong1976 ***@***.***>
Sent: Saturday, February 11, 2023 7:18:34 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] I don't get the newest update (0.6.14) (Issue #52)


I don't get the newest update even though I clicked the update button.

[image]<https://user-images.githubusercontent.com/88898230/218286553-109c0a51-4166-4643-af9d-6c7e4bc450a1.png>

OS: Windows
Obsidian version: 1.1.12, Installer: 1.1.9

**Comment by Liong1976** [comment]
I see,
Thanks, @jp-cen

**Comment by jp-cen** [comment]
This should be working now

**Comment by Liong1976** [comment]
Thanks, @jp-cen
