### ISSUE TITLE
[Bug] 0.6.14 update Frontmatter issue

### ISSUE THREAD

**Issue by Naemy** [Make-md/makemd#53]
When my frontmatter property has sub-properties, it appears as [Object Object] and I cannot access my values anymore when Made.md is enabled, even in « Source » mode.

<img width="317" alt="Capture d’écran 2023-02-12 à 12 06 03" src="https://user-images.githubusercontent.com/2079592/218307322-bbbdc44f-cb07-4ac7-8dda-0653d5377703.png">

**Comment by jp-cen** [comment]
That's currently one of the limitations as noted in the release notes, this will be added in the next version

**Comment by Naemy** [comment]
Okay, I see. Thank you for your reply. 
That being said, you made quite a great plugin. Very useful.
