### ISSUE TITLE
[BUG] Properties Cannot be Created or Modified from Tables

### ISSUE THREAD

**Issue by Bluemoondragon07** [Make-md/makemd#56]
I love the new update with the banner images and showing properties on pages! However, now properties cannot be created from tables (even after clicking `save property`). Properties sync into tables successfully, and the fields can still be changed, but the property type cannot be changed. I have been trying to change a text field to an option field, and a link field to a text field, but the changes will not save. Fields that are automatically option fields will not change if you enable `multiple` either.

**Comment by jp-cen** [comment]
New properties not saving should be fixed in the latest version, let me know if you're still having issues with existing fields

**Comment by Bluemoondragon07** [comment]
Just found that these issues were the result of an outdated version of dataview, not MAKE.md. Sorry about that. Also, source mode as described in #57 is now working as well. Thank you so much for all the hard work you put into maintaining and updating this plug-in!
