### ISSUE TITLE
[Feature Request] Displaying Banners and Inline Properties in Different View Modes

### ISSUE THREAD

**Issue by Bluemoondragon07** [Make-md/makemd#57]
The banners and inline properties are a really exciting new feature and a really impressive implementation. I have a few ideas about slight changes to how they're displayed in different views that I think would enhance the experience these features bring.

# Reading Mode
As of now, the note looks normal in reading mode. To see the properties, banner, backlinks, and note icon, one has to enter editing mode. 
I think in the future it would be nice to show these things in reading mode by default. There could also be an option to turn off seeing properties and backlinks in this mode.
# Live Preview
The plug-in looks great in preview mode and the options are well-implemented. My only suggestion is that, since there is a way to add tags, a way to delete tags as well be added. 
# Source View
I think in Source Mode, the properties and banner settings should disappear, displaying the frontmatter instead. This way, people can change the banner to a custom url and delete tags without turning off the plug-in.
# Cards View in Context Files
This is a minor idea that isn't really important, but it would also be nice if the banners were used as cover images in the Cards view of context files.

Thank you so much for working on this spectacular plug-in!

**Comment by jp-cen** [comment]
Thanks for the feedback! Source mode is now available in the newest update. Reading mode will be in a upcoming update. The cards view not showing the banner seems like a bug, will look into it

**Comment by Bluemoondragon07** [comment]
Closing this because this has all been resolved. Thank you so much for your work on this amazing plugin :)
