### ISSUE TITLE
New notes cannot be automatically saved to the previously set folder

### ISSUE THREAD

**Issue by jkjoker** [Make-md/makemd#6]
New notes cannot be automatically saved to the previously set folder

**Comment by jp-cen** [comment]
Can you elaborate what you mean by previously set folder? 
1. Last opened folder
2. Default Location for new notes in File settings
3. Something else

**Comment by jkjoker** [comment]
I mean Obsidian supports specifying the storage location when create a new note.

**Comment by MatheusPese** [comment]
> Can you elaborate what you mean by previously set folder?
> 
> 1. Last opened folder
> 2. Default Location for new notes in File settings
> 3. Something else

I think he means the second option. Because i have the same issue.

Elaborating further; When you go into obsidian and set the configuration under
"Files & Links" > "Folder to create new notes in"
To a specific folder specific, the "New Note" Button from Make.md does not respect this rule.

**Comment by jp-cen** [comment]
Resolved since 0.5
