### ISSUE TITLE
Contexts in Android

### ISSUE THREAD

**Issue by MarcosDantasdeSantana** [Make-md/makemd#62]
For some reason none of the context create functions work in Mobile:

1. If i try to create a property with context of "File Metadata" the property is not created in the file.

2. If i try to add a tag using the context, it doesn't work.

3. Trying to add a cover from link or file doesn't work.

4. If i edit an existent context value it didn't update in the frontmatter, but if i edit a value in the frontmmater it update the context.

Thanks.

**Comment by jp-cen** [comment]
This is due to the metadata improvements from Obsidian not being yet available on mobile, It’s currently in the insider build and should be available soon.

**Comment by jp-cen** [comment]
The frontmatter API has been released to public in the latest Obsidian mobile, let me know if problem persists
