### ISSUE TITLE
[Feature Requeset] replace the sticker with my own icons

### ISSUE THREAD

**Issue by batman47steam** [Make-md/makemd#63]
Hi, Thanks for this awesome plugin !

I am super exicted with this plugin, but sometimes I want to replace the stickers with my own svg icons, which is more specific to the contents in folder. I hope I can choose the icons from my own icon folder

Thanks in advance

**Comment by jp-cen** [comment]
Glad you're enjoying it. Custom icons is one of the top planned improvements voted in the discord so it will be coming soon

**Comment by IshanChhangani** [comment]
This is marked as closed but can't find a way to add custom icons , can you please let me know.

**Comment by jp-cen** [comment]
There’s a setting to turn on indexing for all svgs as stickers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by IshanChhangani** [comment]
Thank you, that works. But I wanted to get lot of custom svg's shown in the list, that populates up my root directory, is it possible to add path to a folder? Or to make a folder within the root directory?
