### ISSUE TITLE
Feature to convert notes -> into folders (for not to ruin backlinks)

### ISSUE THREAD

**Issue by myownstandard** [Make-md/makemd#64]
Hi!
I don`t know if its only my use case - but it be very heplfull if we could convert simple notes to folders.
I very need it because of Folder structure and nesting folders into folder.
For example use case:

- Project A (folder)
  - Notes about project A (folder)
    - Budget (note)
    - Locations (note)
  - Another notes about project A (folder) 

**And if i have backlink to the note [[Budget]] , but than i need to nest under [[Budget]] for example note January, i cant do it without manually relinking all my backlinks to note [[Budget]] -> Cause now i need to create folder Budget intsead of note Budget and it ruins all backlinks....**

**Comment by jp-cen** [comment]
I'm not quite understanding the effect on the backlinks. What's the original location that your backlinks for Budget point to? Are you referring to the location of the folder note?

**Comment by myownstandard** [comment]
Yea, iam reffering to backlinking to the folder note.
Example (file stucture):
- Project A (folder)
  - Notes about project A (folder note)
    - **Budget (note)** 
    - Locations (note)
  - Another notes about project A (folder note) 

I have a note "Work" for example and it has a backlink to the note "Budget". But one day the note "Budget" will be replaced with the folder with the same name. For this purpose i need to delete original note "Budget" and create new folder note "Budget".

- Project A (folder)
  - Notes about project A (folder note)
    - **Budget (folder note)**
        - January budget (note) 
    - Locations (note)
  - Another notes about project A (folder note)  

But all the backlinks will stop working (related to Budget because i deleted the original note and created foldet Budget instead.)
So would be great if we could have a command to conver note "Budget" to folder "Budget" to preserve all the backlinks.
