### ISSUE TITLE
[BUG] Bad handling of nested YAML

### ISSUE THREAD

**Issue by MarcosDantasdeSantana** [Make-md/makemd#67]
# Problem

If you have a nested YAML like the folowing, the Make.md Context is not able to handle the values.

```md
---
nested:
  children: value
  anotherchild: value
---
```

They are displayed like this:

![Screenshots_2023-02-23-10-54-28.png](https://user-images.githubusercontent.com/82475903/220927670-bd7b712e-afed-4c0c-8955-29dd1fc07d8c.png)

And if i make an edit direct in the Context, it will format the md to this:

```md
nested: '{"children":"valua","anotherchild":"value"}'
```

# Desirable result

Explicit show the children propertys as propertys editable in the Context.

**Comment by jp-cen** [comment]
This should be working for one-level key value (no second level nesting support) in the latest version

**Comment by MarcosDantasdeSantana** [comment]
In the last update this doesn't appears now.
