### ISSUE TITLE
[Feature Request] Add an option to disable backlinks from showing inside of documments.

### ISSUE THREAD

**Issue by aravezskinteeth** [Make-md/makemd#73]
I have the same problem as #44. Many of my documents have 100+ backlinks which makes impossible to open them. Even disabling the backlinks core plugin and restarting my vault did not solve the problem.

What solved the problem was to disable the `Context` feature, however, that also made the the banners, emoji and the metadata (not the `yaml`) disappear. 

I hope you can separate the backlinks from the Context in settings, so we can toggle it off without disabling the other.

Otherwise, I really love this plugin. I hope you can take this into account.

**Comment by jp-cen** [comment]
The toggle is under the Flow Editor section

**Comment by aravezskinteeth** [comment]
Oh, never mind, you're right. I found it in `Show Inline Backlinks (Inline Context required)`. Thank you.

**Comment by Morganwan90** [comment]
> The toggle is under the Flow Editor section

I tried but the backlink is still there..
![截图_20230728232015](https://github.com/Make-md/makemd/assets/61633409/efe422d4-66de-45db-a2e8-6e1b29921223)
