### ISSUE TITLE
[BUG] Wrong (synced) inline title, context and banner when displaying more than one note

### ISSUE THREAD

**Issue by ernestowgg** [Make-md/makemd#76]
Whenever I display more than one note (stacked or parallel), inline title, context and banner will sync to whatever note currently has the focus. Result: all other notes show the same, wrong information.

**Comment by jp-cen** [comment]
This is currently an issue with reading view, fix will be available soon with 0.7 update

**Comment by ernestowgg** [comment]
Thanks for replying. I really love the plugin.

**Comment by jp-cen** [comment]
update is now available

**Comment by RomanMunar** [comment]
Still occurring at v8.0 both in normal and stack tabs. Much noticable on stack tabs.
