### ISSUE TITLE
Can't type in file created by using [[NewNoteTitle]] while having enabled Make.md

### ISSUE THREAD

**Issue by xBlady** [Make-md/makemd#78]
Hello!

I Can't type in file created by using [[NewNoteTitle]] while having enabled Make.md

There's no place I can place my coursor. 

![image](https://user-images.githubusercontent.com/7155031/225417062-f318007d-63e9-4bba-806c-21b10ada0bd9.png)

**Comment by jp-cen** [comment]
There’s an issue related to inline backlinks that’s causing this, you can turn it off in Flow Editor section of Make.md settings. A fix will be released as part of 0.7 update.

**Comment by rexelbartolome** [comment]
> There’s an issue related to inline backlinks that’s causing this, you can turn it off in Flow Editor section of Make.md settings. A fix will be released as part of 0.7 update.

thank you, i've been scratching my head for this

**Comment by jp-cen** [comment]
fixed in latest version
