### ISSUE TITLE
[Bug] the name of pinned spaces not support emoji characters

### ISSUE THREAD

**Issue by TenviLi** [Make-md/makemd#87]
![](https://user-images.githubusercontent.com/30214981/229310990-b77b826a-7497-4d9a-9fd3-ccc8acc9a6d3.png)

![](https://user-images.githubusercontent.com/30214981/229311002-e962f5ba-b059-4f5c-a555-9a9a7fd176a2.png)

![](https://user-images.githubusercontent.com/30214981/229310938-28b70b3a-4402-4759-8985-96d3f7651e27.png)

![](https://user-images.githubusercontent.com/30214981/229310956-2d820870-cdac-4ed1-a2c3-d6aa87248252.png)

**Comment by TenviLi** [comment]
When a Spaces is pinned, its name will not support emoji and other characters in the tab, and it will display as garbled code even though setting it as emoji and other special characters is for the convenience of users to identify.

**Comment by jp-cen** [comment]
Will take a look at that, but you can assign an emoji to the space name by right clicking the space. Using emoji as space name may cause other compatibility issues with sync services
