### ISSUE TITLE
Make “ToC” list searchable

### ISSUE THREAD

**Issue by DutchPete** [Make-md/makemd#9]
*Fanny.md* brought [this feature](https://discord.com/channels/799706244264362024/1037512613220843540/1044192861115125841) to my attention, which is probably the same as #5. It is very useful indeed.

It would be useful to be able to use ⌘+F to search the titles, which is not possible at present.

BTW, this feature is hidden, people are not aware of it: *meireles* was also alerted to it by *Fanny.md*. Perhaps it could be made more explicit.

**Comment by jp-cen** [comment]
Resolved since 0.5
