### ISSUE TITLE
search support omnisearch

### ISSUE THREAD

**Issue by zhaihao** [Make-md/makemd#94]
search support omnisearch please.

https://github.com/scambier/obsidian-omnisearch

**Comment by jp-cen** [comment]
Can you elaborate? 
Do you want 
- Blink to have full text search like omnisearch 
- Omnisearch to replace Blink as the search button
- Omnisearch currently not finding certain things created by make.md that you would like

**Comment by zhaihao** [comment]
Thank you for your response。“Omnisearch to replace Blink as the search button”，that's what I wanted
