### ISSUE TITLE
[BUG] Plugins tries to load mk-file-view with an error in sidebar in Obsidian 1.2.2

### ISSUE THREAD

**Issue by OmniNaut** [Make-md/makemd#95]
![image](https://user-images.githubusercontent.com/110312864/230543727-edcef455-3623-4356-a52f-e0f9a92eafa2.png)

![image](https://user-images.githubusercontent.com/110312864/230543617-7a8d2497-f00c-470b-a86e-8a9b9c4082c7.png)

Plugin version: 0.7.7
Spaces: disabled
Context: disabled
Blink: disabled
Flow: enabled (also with flow disabled error appears after restart of Obsidian

Obsidian: 1.2.2
Windows 11

**Comment by jp-cen** [comment]
Thanks for reporting this, will be patched in the next update

**Comment by jp-cen** [comment]
Fixed in latest version
