### ISSUE TITLE
[BUG] Folder view not working.

### ISSUE THREAD

**Issue by FootPrintStudio** [Make-md/makemd#96]
The folder view is one of the main reasons I was attracted to this plugin; however, it constantly breaks. The files are often not recognised and disappear when I try to change the view or any other setting, the only way to get them back is to delete the context file that is created by the folder and start again. The few times I got it to work for a bit it was great, it allowed me to minimise the nesting of folders since I could just add extra metadata and then group via that and get the same effect, but like I said it seems to inevitably break after a bit of use. All that I can gather is that it's failing to read the files in the folder, if I add a new file it will recognise it for a bit but in a few instances that has eventually disappeared too.

**Comment by jp-cen** [comment]
Thanks for the feedback, are you currently on the latest version 0.7.7 and experiencing these issues? 0.7 was rewritten to resolve many of the issues related to folder and tag context (view) reliability. There are still some issues that are being solved for example turning off Folder Note is currently breaking the view. However, if you're on the latest version and experiencing these issues, any logs that you can provide would be much appreciated for helping tracking down these issues.

**Comment by FootPrintStudio** [comment]
Yes, I'm currently on version 0.7.7, I don't want to speak too soon but it seems to be functioning now. Unfortunately, I uninstalled the plugin and a few others that I wasn't using and re-installed MAKE.md without tracking what I changed.

Folder Note is also disabled; however, when trying to fix the problem I tried a few times with it on and off without a notable difference. Folder Note Location is however still enabled, so maybe that plays a role in the issue.

These are the plugins I think I removed, which may be conflicting in some way.
 - Advanced Tables
 - Excel to Markdown Table
 - Image Layouts
 - Longform
 - Markdown Formatting Assistant
 - Reference Map
 - Tag Wrangler

When I initially installed and enabled the plugin I also immediately enabled the compatibility mode since I have a few plugins; however, after reinstalling I left that off too. And, both Blink and Flow are disabled, I'm only using Spaces and Context.

Since I'm not 100% certain if the folders are actually working now, here are the remaining plugins I have enabled.

 - Banners (Doesn't work well unless the Context Explorer panel is docked)
 - Callout Manager
 - Dialogue
 - Fantasy Calendar
 - File Cleaner
 - Find Orphaned Files and Broken Links
 - Image Captions
 - Image Toolkit
 - Note Linker
 - Numerals
 - Obsidian Columns
 - Obsidian Leaflet
 - Open Gate
 - Paste as HTML
 - Pending Notes
 - Quoth
 - Regex Find/Replace
 - Sort & Permute Lines
 - Timeline

**Comment by jp-cen** [comment]
The issue that was caused by folder notes is now fixed, the issue might be caused by that issue and the settings currently don't take effect immediately without a restart so toggling it previously might not have fixed it when you previously tried it.

**Comment by FootPrintStudio** [comment]
I've played around with changing file names and folder names, trying to see if I can cause the folder view to break again and it does indeed seem to be working. Thanks for your efforts, it's a great plugin.
